---
title: "Predicting NBA Allstars"
author: "Mohammed Bukhattala, Justin Clifton, Maxwell Pitney, Graham Swain"
date: "4/24/2021"
abstract: "Each NBA season, 24 players are selected to be allstars. The selection process involves fans voting for players they would like to see. Players voted in by fans are selected as starters and then coaches select the 7 bench players. We offer several models for predicting if a player is an allstar based on various statistics tracked throughout the season."
output: html_document
---

```{r}
library(readr)
library(tibble)
library(ggplot2)
#library(GGally)
library(dplyr)
DF = read.csv("NBA_Stats_MVP.csv", header = TRUE)
nba_df = na.omit(DF)
names(nba_df)
nba_df$was_mvp = as.logical(nba_df$was_mvp)
nbaTib = as_tibble(nba_df)
cleanDF = select(nbaTib, -c(Pos, Tm, Name, Year, is_allstar))

# ggplot(nbaTib, aes(x = factor(is_allstar), fill = is_allstar)) +
#     geom_bar()
```


```{r}
ggplot(data = nbaTib) +
  geom_point(mapping = aes(x = FGA, y = FG, color = was_mvp, shape=was_mvp))
```


```{r}
ggplot(filter(DF, was_mvp == 1), aes(x = factor(Pos), fill = Pos)) +
    geom_bar() +
    scale_y_continuous(breaks=c(4,6,8,10,12)) +
    labs(title="NBA MVPS by Position (1974 - 2017)",
        x ="Position", y = "frequency")
```
```{r}
ggplot(filter(nbaTib, was_mvp == 1), aes(x = Pos, fill = Pos)) +
    geom_bar() +
    scale_y_continuous(breaks=c(4,6,8,10)) +
    labs(title="NBA MVPS by Position (1983 - 2017)",
        x ="Position", y = "frequency")
```


# Modeling

First we split the data into training and testing.
```{r}
train = sample(dim(cleanDF)[1], dim(cleanDF)[1]/2)
test = cleanDF[-train, ]
```

We will now perform logistic regression.
```{r}

```


```{r}

```
Although the models accuracy is decently high, it is a trivial problem to predict who is NOT an allstar. We would like to predict who IS an allstar. Therefore, we are concerned with the recall (i.e. the true positive rate) of the model. In this case, the recall is 36%.




